use std::path::Path;
use std::path::PathBuf;
use std::str::FromStr;

use super::{Error, Image, Lod, Map, Page};
use crate::PathSet;
use crate::indexed::VecWithIndex;

crate::make_index!(ImageIndex, usize, true);
crate::make_index!(MapIndex, usize, true);
crate::make_index!(PageIndex, usize, true);

pub trait OutputMap: std::fmt::Debug {
    fn img_path(&self, image_src: &Path, lod: Lod) -> Result<PathBuf, Error>;
}

impl OutputMap for PathBuf {
    fn img_path(&self, image_src: &Path, lod: Lod) -> Result<PathBuf, Error> {
        let image_src = lod.image_path(image_src)?;
        // Drop the directories
        Ok(self.join(image_src.file_name().unwrap()))
    }
}

/// Create the Album
///
/// Set the output map
///
/// Derive the data
#[derive(Debug)]
pub struct Album {
    /// Paths to use to find files such as the album descriptor, if any
    path_set: PathSet,
    /// Source directories for the images; must be set prior to adding images
    ///
    /// This should be a PathSet, generated by adding paths which are directories found from path_set for a given image src directory
    image_srcs: Vec<PathBuf>,
    /// Images in the album, indexed by image name
    images: VecWithIndex<'static, String, ImageIndex, Image, true>,
    /// Images in the album, indexed by image name
    maps: VecWithIndex<'static, String, MapIndex, Map, true>,
    /// Pages in the album, indexed by page name
    pages: VecWithIndex<'static, String, PageIndex, Page, true>,
    /// Levels of detail required for the images
    ///
    /// These are in pixels, sorted smallest to largst
    lod: Vec<Lod>,
    /// Output directory mapping
    output_map: Box<dyn OutputMap>,
}

impl std::default::Default for Album {
    fn default() -> Self {
        Self {
            path_set: PathSet::default(),
            image_srcs: vec![],
            images: VecWithIndex::default(),
            maps: VecWithIndex::default(),
            pages: VecWithIndex::default(),
            lod: vec![],
            output_map: Box::new(PathBuf::new().join("output")),
        }
    }
}

impl Album {
    pub fn new(path_set: &PathSet) -> Self {
        let mut s = Self::default();
        s.path_set = path_set.clone();
        s
    }

    pub fn set_output_root(&mut self, root: &str) {
        let path: PathBuf = root.into();
        self.output_map = Box::new(path);
    }

    pub fn add_lod(&mut self, lod: f32) -> Result<(), Error> {
        let lod = Lod::of_f32(lod)?;
        self.lod.push(lod);
        self.lod.sort();
        Ok(())
    }

    pub fn find_image_path<P: AsRef<Path>>(&self, path: P) -> Result<PathBuf, Error> {
        Ok(self.path_set.find_file_err(path)?)
    }

    pub fn add_image_src(&mut self, s: &str) -> Result<(), Error> {
        let p = PathBuf::from_str(s).unwrap(); // The conversion is infallible
        self.image_srcs.push(p);
        Ok(())
    }

    pub fn add_image(&mut self, img: Image) -> Result<ImageIndex, Error> {
        let name = img.name().to_owned();
        let err_name = name.clone();
        self.images
            .insert(name, |_| img)
            .map_err(|_e| Error::AlbumAlreadyContainsImage {
                image_name: err_name,
            })
    }

    pub fn add_map(&mut self, map: Map) -> Result<MapIndex, Error> {
        let name = map.name().to_owned();
        let err_name = name.clone();
        self.maps
            .insert(name, |_| map)
            .map_err(|_e| Error::AlbumAlreadyContainsMap { map_name: err_name })
    }

    pub fn add_page(&mut self, page: Page) -> Result<PageIndex, Error> {
        let name = page.name().to_owned();
        let err_name = name.clone();
        self.pages
            .insert(name, |_| page)
            .map_err(|_e| Error::AlbumAlreadyContainsPage {
                page_name: err_name,
            })
    }

    pub fn find_image_index(&self, image_name: &str) -> Result<ImageIndex, Error> {
        if let Some(idx) = self.images.find_key(image_name) {
            Ok(idx)
        } else {
            Err(Error::AlbumDoesNotContainImage {
                image_name: image_name.to_owned(),
            })
        }
    }
    pub fn image(&self, idx: ImageIndex) -> Option<&Image> {
        self.images.get(idx)
    }

    pub fn find_page_index(&self, page_name: &str) -> Result<PageIndex, Error> {
        if let Some(idx) = self.pages.find_key(page_name) {
            Ok(idx)
        } else {
            Err(Error::AlbumDoesNotContainPage {
                page_name: page_name.to_owned(),
            })
        }
    }

    pub fn page(&self, idx: PageIndex) -> Option<&Page> {
        self.pages.get(idx)
    }

    pub fn derive_data(&mut self) -> Result<(), Error> {
        eprintln!("Deriving data...");
        let images = &mut self.images;
        let output_map = &self.output_map;
        eprintln!("Creating lod for images...");
        for image in images.iter_mut() {
            for lod in self.lod.iter().copied() {
                if !image.add_lod(lod) {
                    break;
                }
            }
        }
        eprintln!("Loading image data for specifc LODs...");
        for image in images.iter_mut() {
            // eprintln!("   ... {}", image.src().display());
            let image_src = image.src().to_owned();
            for image_data in image.image_data_mut().iter_mut() {
                let lod = image_data.lod();
                let path = output_map.img_path(&image_src, lod)?;
                image_data.set_image_file(path);
            }
        }
        Ok(())
    }

    pub fn images<'iter>(&'iter self) -> std::slice::Iter<'iter, Image> {
        self.images.iter()
    }

    pub fn image_tags<'iter>(&'iter self) -> impl Iterator<Item = &'iter String> {
        self.images.keys()
    }

    pub fn maps<'iter>(&'iter self) -> std::slice::Iter<'iter, Map> {
        self.maps.iter()
    }

    pub fn map_tags<'iter>(&'iter self) -> impl Iterator<Item = &'iter String> {
        self.maps.keys()
    }

    pub fn pages<'iter>(&'iter self) -> std::slice::Iter<'iter, Page> {
        self.pages.iter()
    }

    pub fn page_tags<'iter>(&'iter self) -> impl Iterator<Item = &'iter String> {
        self.pages.keys()
    }

    pub fn make_page_indexes(&self) {
        for p in self.pages.iter() {
            p.make_page_index(&self);
        }
    }
}
