[package]
name = "photo-album-wasm"
edition.workspace = true
version.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
geo-nd-wasm.workspace = true
