[package]
name = "photo-album"
edition.workspace = true
version.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
thiserror.workspace = true
thunderclap.workspace = true
photo-album-core.workspace = true
photo-album-web.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
